# Generated by Django 6.0.1 on 2026-01-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('date', models.DateField(verbose_name='Fecha de publicación')),
                ('content', models.TextField(verbose_name='Contenido o Resumen')),
                ('url', models.URLField(max_length=500, verbose_name='Enlace externo')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-date'],
            },
        ),
    ]
