# Generated by Django 6.0.1 on 2026-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, default='logo.png', max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
    ]
