# Generated by Django 6.0.1 on 2026-01-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_blogpost_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(blank=True, default='logo.png', max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
    ]
